/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDecisionsRouteImport } from './routes/admin.decisions'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminGradesRouteImport } from './routes/admin.grades'
import { Route as AdminKitRouteImport } from './routes/admin.kit'
import { Route as AuthTestRouteImport } from './routes/auth/test'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as PlanIndexRouteImport } from './routes/plan.index'
import { Route as PlanImportRouteImport } from './routes/plan.import'
import { Route as PlanProblemsRouteImport } from './routes/plan.problems'
import { Route as PlanSamplesRouteImport } from './routes/plan.samples'
import { Route as PlanSearchRouteImport } from './routes/plan.search'
import { Route as PlanSharedRouteImport } from './routes/plan_.shared'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ReviewsMineRouteImport } from './routes/reviews.mine'
import { Route as ReviewsPolicyRouteImport } from './routes/reviews.policy'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as ScheduleBlocksRouteImport } from './routes/schedule.blocks'
import { Route as ScheduleCoursesRouteImport } from './routes/schedule.courses'
import { Route as ScheduleExportRouteImport } from './routes/schedule.export'
import { Route as ScheduleGenerateRouteImport } from './routes/schedule.generate'
import { Route as ScheduleProblemsRouteImport } from './routes/schedule.problems'
import { Route as ScheduleRegisterRouteImport } from './routes/schedule.register'
import { Route as ScheduleSearchRouteImport } from './routes/schedule.search'
import { Route as ScheduleTravelRouteImport } from './routes/schedule.travel'
import { Route as SettingsNotificationsRouteImport } from './routes/settings_.notifications'
import { Route as TodoIndexRouteImport } from './routes/todo.index'
import { Route as TodoConnectRouteImport } from './routes/todo.connect'
import { Route as ReviewsCoursesCodeRouteImport } from './routes/reviews.courses.$code'
import { Route as ReviewsInstructorsIdRouteImport } from './routes/reviews.instructors.$id'
import { Route as ScheduleConnectionConnectionIdRouteImport } from './routes/schedule.connection.$connectionId'
import { Route as ScheduleCourseCodeRouteImport } from './routes/schedule.course.$code'
import { Route as ScheduleResultResultIdRouteImport } from './routes/schedule.result.$resultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDecisionsRoute = AdminDecisionsRouteImport.update({
  id: '/admin/decisions',
  path: '/admin/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGradesRoute = AdminGradesRouteImport.update({
  id: '/admin/grades',
  path: '/admin/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitRoute = AdminKitRouteImport.update({
  id: '/admin/kit',
  path: '/admin/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth/test',
  path: '/auth/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanRoute,
} as any)
const PlanImportRoute = PlanImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PlanRoute,
} as any)
const PlanProblemsRoute = PlanProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => PlanRoute,
} as any)
const PlanSamplesRoute = PlanSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => PlanRoute,
} as any)
const PlanSearchRoute = PlanSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PlanRoute,
} as any)
const PlanSharedRoute = PlanSharedRouteImport.update({
  id: '/plan_/shared',
  path: '/plan/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsMineRoute = ReviewsMineRouteImport.update({
  id: '/reviews/mine',
  path: '/reviews/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsPolicyRoute = ReviewsPolicyRouteImport.update({
  id: '/reviews/policy',
  path: '/reviews/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleBlocksRoute = ScheduleBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleCoursesRoute = ScheduleCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleExportRoute = ScheduleExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleGenerateRoute = ScheduleGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleProblemsRoute = ScheduleProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleRegisterRoute = ScheduleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleSearchRoute = ScheduleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleTravelRoute = ScheduleTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => ScheduleRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings_/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIndexRoute = TodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoConnectRoute = TodoConnectRouteImport.update({
  id: '/todo/connect',
  path: '/todo/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsCoursesCodeRoute = ReviewsCoursesCodeRouteImport.update({
  id: '/reviews/courses/$code',
  path: '/reviews/courses/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsInstructorsIdRoute = ReviewsInstructorsIdRouteImport.update({
  id: '/reviews/instructors/$id',
  path: '/reviews/instructors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleConnectionConnectionIdRoute =
  ScheduleConnectionConnectionIdRouteImport.update({
    id: '/connection/$connectionId',
    path: '/connection/$connectionId',
    getParentRoute: () => ScheduleRoute,
  } as any)
const ScheduleCourseCodeRoute = ScheduleCourseCodeRouteImport.update({
  id: '/course/$code',
  path: '/course/$code',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleResultResultIdRoute = ScheduleResultResultIdRouteImport.update({
  id: '/result/$resultId',
  path: '/result/$resultId',
  getParentRoute: () => ScheduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/plan': typeof PlanRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/kit': typeof AdminKitRoute
  '/auth/test': typeof AuthTestRoute
  '/plan/import': typeof PlanImportRoute
  '/plan/problems': typeof PlanProblemsRoute
  '/plan/samples': typeof PlanSamplesRoute
  '/plan/search': typeof PlanSearchRoute
  '/plan/shared': typeof PlanSharedRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/mine': typeof ReviewsMineRoute
  '/reviews/policy': typeof ReviewsPolicyRoute
  '/schedule/blocks': typeof ScheduleBlocksRoute
  '/schedule/courses': typeof ScheduleCoursesRoute
  '/schedule/export': typeof ScheduleExportRoute
  '/schedule/generate': typeof ScheduleGenerateRoute
  '/schedule/problems': typeof ScheduleProblemsRoute
  '/schedule/register': typeof ScheduleRegisterRoute
  '/schedule/search': typeof ScheduleSearchRoute
  '/schedule/travel': typeof ScheduleTravelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/todo/connect': typeof TodoConnectRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/todo/': typeof TodoIndexRoute
  '/reviews/courses/$code': typeof ReviewsCoursesCodeRoute
  '/reviews/instructors/$id': typeof ReviewsInstructorsIdRoute
  '/schedule/connection/$connectionId': typeof ScheduleConnectionConnectionIdRoute
  '/schedule/course/$code': typeof ScheduleCourseCodeRoute
  '/schedule/result/$resultId': typeof ScheduleResultResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/kit': typeof AdminKitRoute
  '/auth/test': typeof AuthTestRoute
  '/plan/import': typeof PlanImportRoute
  '/plan/problems': typeof PlanProblemsRoute
  '/plan/samples': typeof PlanSamplesRoute
  '/plan/search': typeof PlanSearchRoute
  '/plan/shared': typeof PlanSharedRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/mine': typeof ReviewsMineRoute
  '/reviews/policy': typeof ReviewsPolicyRoute
  '/schedule/blocks': typeof ScheduleBlocksRoute
  '/schedule/courses': typeof ScheduleCoursesRoute
  '/schedule/export': typeof ScheduleExportRoute
  '/schedule/generate': typeof ScheduleGenerateRoute
  '/schedule/problems': typeof ScheduleProblemsRoute
  '/schedule/register': typeof ScheduleRegisterRoute
  '/schedule/search': typeof ScheduleSearchRoute
  '/schedule/travel': typeof ScheduleTravelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/todo/connect': typeof TodoConnectRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/plan': typeof PlanIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/todo': typeof TodoIndexRoute
  '/reviews/courses/$code': typeof ReviewsCoursesCodeRoute
  '/reviews/instructors/$id': typeof ReviewsInstructorsIdRoute
  '/schedule/connection/$connectionId': typeof ScheduleConnectionConnectionIdRoute
  '/schedule/course/$code': typeof ScheduleCourseCodeRoute
  '/schedule/result/$resultId': typeof ScheduleResultResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/plan': typeof PlanRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/admin/decisions': typeof AdminDecisionsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/kit': typeof AdminKitRoute
  '/auth/test': typeof AuthTestRoute
  '/plan/import': typeof PlanImportRoute
  '/plan/problems': typeof PlanProblemsRoute
  '/plan/samples': typeof PlanSamplesRoute
  '/plan/search': typeof PlanSearchRoute
  '/plan_/shared': typeof PlanSharedRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/mine': typeof ReviewsMineRoute
  '/reviews/policy': typeof ReviewsPolicyRoute
  '/schedule/blocks': typeof ScheduleBlocksRoute
  '/schedule/courses': typeof ScheduleCoursesRoute
  '/schedule/export': typeof ScheduleExportRoute
  '/schedule/generate': typeof ScheduleGenerateRoute
  '/schedule/problems': typeof ScheduleProblemsRoute
  '/schedule/register': typeof ScheduleRegisterRoute
  '/schedule/search': typeof ScheduleSearchRoute
  '/schedule/travel': typeof ScheduleTravelRoute
  '/settings_/notifications': typeof SettingsNotificationsRoute
  '/todo/connect': typeof TodoConnectRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/todo/': typeof TodoIndexRoute
  '/reviews/courses/$code': typeof ReviewsCoursesCodeRoute
  '/reviews/instructors/$id': typeof ReviewsInstructorsIdRoute
  '/schedule/connection/$connectionId': typeof ScheduleConnectionConnectionIdRoute
  '/schedule/course/$code': typeof ScheduleCourseCodeRoute
  '/schedule/result/$resultId': typeof ScheduleResultResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/plan'
    | '/privacy'
    | '/schedule'
    | '/settings'
    | '/signin'
    | '/admin/decisions'
    | '/admin/feedback'
    | '/admin/grades'
    | '/admin/kit'
    | '/auth/test'
    | '/plan/import'
    | '/plan/problems'
    | '/plan/samples'
    | '/plan/search'
    | '/plan/shared'
    | '/reviews/$slug'
    | '/reviews/mine'
    | '/reviews/policy'
    | '/schedule/blocks'
    | '/schedule/courses'
    | '/schedule/export'
    | '/schedule/generate'
    | '/schedule/problems'
    | '/schedule/register'
    | '/schedule/search'
    | '/schedule/travel'
    | '/settings/notifications'
    | '/todo/connect'
    | '/admin/'
    | '/chat/'
    | '/plan/'
    | '/reviews/'
    | '/schedule/'
    | '/todo/'
    | '/reviews/courses/$code'
    | '/reviews/instructors/$id'
    | '/schedule/connection/$connectionId'
    | '/schedule/course/$code'
    | '/schedule/result/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/privacy'
    | '/settings'
    | '/signin'
    | '/admin/decisions'
    | '/admin/feedback'
    | '/admin/grades'
    | '/admin/kit'
    | '/auth/test'
    | '/plan/import'
    | '/plan/problems'
    | '/plan/samples'
    | '/plan/search'
    | '/plan/shared'
    | '/reviews/$slug'
    | '/reviews/mine'
    | '/reviews/policy'
    | '/schedule/blocks'
    | '/schedule/courses'
    | '/schedule/export'
    | '/schedule/generate'
    | '/schedule/problems'
    | '/schedule/register'
    | '/schedule/search'
    | '/schedule/travel'
    | '/settings/notifications'
    | '/todo/connect'
    | '/admin'
    | '/chat'
    | '/plan'
    | '/reviews'
    | '/schedule'
    | '/todo'
    | '/reviews/courses/$code'
    | '/reviews/instructors/$id'
    | '/schedule/connection/$connectionId'
    | '/schedule/course/$code'
    | '/schedule/result/$resultId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/plan'
    | '/privacy'
    | '/schedule'
    | '/settings'
    | '/signin'
    | '/admin/decisions'
    | '/admin/feedback'
    | '/admin/grades'
    | '/admin/kit'
    | '/auth/test'
    | '/plan/import'
    | '/plan/problems'
    | '/plan/samples'
    | '/plan/search'
    | '/plan_/shared'
    | '/reviews/$slug'
    | '/reviews/mine'
    | '/reviews/policy'
    | '/schedule/blocks'
    | '/schedule/courses'
    | '/schedule/export'
    | '/schedule/generate'
    | '/schedule/problems'
    | '/schedule/register'
    | '/schedule/search'
    | '/schedule/travel'
    | '/settings_/notifications'
    | '/todo/connect'
    | '/admin/'
    | '/chat/'
    | '/plan/'
    | '/reviews/'
    | '/schedule/'
    | '/todo/'
    | '/reviews/courses/$code'
    | '/reviews/instructors/$id'
    | '/schedule/connection/$connectionId'
    | '/schedule/course/$code'
    | '/schedule/result/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  PlanRoute: typeof PlanRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ScheduleRoute: typeof ScheduleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  AdminDecisionsRoute: typeof AdminDecisionsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminGradesRoute: typeof AdminGradesRoute
  AdminKitRoute: typeof AdminKitRoute
  AuthTestRoute: typeof AuthTestRoute
  PlanSharedRoute: typeof PlanSharedRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  ReviewsMineRoute: typeof ReviewsMineRoute
  ReviewsPolicyRoute: typeof ReviewsPolicyRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  TodoConnectRoute: typeof TodoConnectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  TodoIndexRoute: typeof TodoIndexRoute
  ReviewsCoursesCodeRoute: typeof ReviewsCoursesCodeRoute
  ReviewsInstructorsIdRoute: typeof ReviewsInstructorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/decisions': {
      id: '/admin/decisions'
      path: '/admin/decisions'
      fullPath: '/admin/decisions'
      preLoaderRoute: typeof AdminDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/grades': {
      id: '/admin/grades'
      path: '/admin/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AdminGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kit': {
      id: '/admin/kit'
      path: '/admin/kit'
      fullPath: '/admin/kit'
      preLoaderRoute: typeof AdminKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/test': {
      id: '/auth/test'
      path: '/auth/test'
      fullPath: '/auth/test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/import': {
      id: '/plan/import'
      path: '/import'
      fullPath: '/plan/import'
      preLoaderRoute: typeof PlanImportRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/problems': {
      id: '/plan/problems'
      path: '/problems'
      fullPath: '/plan/problems'
      preLoaderRoute: typeof PlanProblemsRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/samples': {
      id: '/plan/samples'
      path: '/samples'
      fullPath: '/plan/samples'
      preLoaderRoute: typeof PlanSamplesRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/search': {
      id: '/plan/search'
      path: '/search'
      fullPath: '/plan/search'
      preLoaderRoute: typeof PlanSearchRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan_/shared': {
      id: '/plan_/shared'
      path: '/plan/shared'
      fullPath: '/plan/shared'
      preLoaderRoute: typeof PlanSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/mine': {
      id: '/reviews/mine'
      path: '/reviews/mine'
      fullPath: '/reviews/mine'
      preLoaderRoute: typeof ReviewsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/policy': {
      id: '/reviews/policy'
      path: '/reviews/policy'
      fullPath: '/reviews/policy'
      preLoaderRoute: typeof ReviewsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/blocks': {
      id: '/schedule/blocks'
      path: '/blocks'
      fullPath: '/schedule/blocks'
      preLoaderRoute: typeof ScheduleBlocksRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/courses': {
      id: '/schedule/courses'
      path: '/courses'
      fullPath: '/schedule/courses'
      preLoaderRoute: typeof ScheduleCoursesRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/export': {
      id: '/schedule/export'
      path: '/export'
      fullPath: '/schedule/export'
      preLoaderRoute: typeof ScheduleExportRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/generate': {
      id: '/schedule/generate'
      path: '/generate'
      fullPath: '/schedule/generate'
      preLoaderRoute: typeof ScheduleGenerateRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/problems': {
      id: '/schedule/problems'
      path: '/problems'
      fullPath: '/schedule/problems'
      preLoaderRoute: typeof ScheduleProblemsRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/register': {
      id: '/schedule/register'
      path: '/register'
      fullPath: '/schedule/register'
      preLoaderRoute: typeof ScheduleRegisterRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/search': {
      id: '/schedule/search'
      path: '/search'
      fullPath: '/schedule/search'
      preLoaderRoute: typeof ScheduleSearchRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/travel': {
      id: '/schedule/travel'
      path: '/travel'
      fullPath: '/schedule/travel'
      preLoaderRoute: typeof ScheduleTravelRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/settings_/notifications': {
      id: '/settings_/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/': {
      id: '/todo/'
      path: '/todo'
      fullPath: '/todo/'
      preLoaderRoute: typeof TodoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/connect': {
      id: '/todo/connect'
      path: '/todo/connect'
      fullPath: '/todo/connect'
      preLoaderRoute: typeof TodoConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/courses/$code': {
      id: '/reviews/courses/$code'
      path: '/reviews/courses/$code'
      fullPath: '/reviews/courses/$code'
      preLoaderRoute: typeof ReviewsCoursesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/instructors/$id': {
      id: '/reviews/instructors/$id'
      path: '/reviews/instructors/$id'
      fullPath: '/reviews/instructors/$id'
      preLoaderRoute: typeof ReviewsInstructorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/connection/$connectionId': {
      id: '/schedule/connection/$connectionId'
      path: '/connection/$connectionId'
      fullPath: '/schedule/connection/$connectionId'
      preLoaderRoute: typeof ScheduleConnectionConnectionIdRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/course/$code': {
      id: '/schedule/course/$code'
      path: '/course/$code'
      fullPath: '/schedule/course/$code'
      preLoaderRoute: typeof ScheduleCourseCodeRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/result/$resultId': {
      id: '/schedule/result/$resultId'
      path: '/result/$resultId'
      fullPath: '/schedule/result/$resultId'
      preLoaderRoute: typeof ScheduleResultResultIdRouteImport
      parentRoute: typeof ScheduleRoute
    }
  }
}

interface PlanRouteChildren {
  PlanImportRoute: typeof PlanImportRoute
  PlanProblemsRoute: typeof PlanProblemsRoute
  PlanSamplesRoute: typeof PlanSamplesRoute
  PlanSearchRoute: typeof PlanSearchRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanImportRoute: PlanImportRoute,
  PlanProblemsRoute: PlanProblemsRoute,
  PlanSamplesRoute: PlanSamplesRoute,
  PlanSearchRoute: PlanSearchRoute,
  PlanIndexRoute: PlanIndexRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

interface ScheduleRouteChildren {
  ScheduleBlocksRoute: typeof ScheduleBlocksRoute
  ScheduleCoursesRoute: typeof ScheduleCoursesRoute
  ScheduleExportRoute: typeof ScheduleExportRoute
  ScheduleGenerateRoute: typeof ScheduleGenerateRoute
  ScheduleProblemsRoute: typeof ScheduleProblemsRoute
  ScheduleRegisterRoute: typeof ScheduleRegisterRoute
  ScheduleSearchRoute: typeof ScheduleSearchRoute
  ScheduleTravelRoute: typeof ScheduleTravelRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ScheduleConnectionConnectionIdRoute: typeof ScheduleConnectionConnectionIdRoute
  ScheduleCourseCodeRoute: typeof ScheduleCourseCodeRoute
  ScheduleResultResultIdRoute: typeof ScheduleResultResultIdRoute
}

const ScheduleRouteChildren: ScheduleRouteChildren = {
  ScheduleBlocksRoute: ScheduleBlocksRoute,
  ScheduleCoursesRoute: ScheduleCoursesRoute,
  ScheduleExportRoute: ScheduleExportRoute,
  ScheduleGenerateRoute: ScheduleGenerateRoute,
  ScheduleProblemsRoute: ScheduleProblemsRoute,
  ScheduleRegisterRoute: ScheduleRegisterRoute,
  ScheduleSearchRoute: ScheduleSearchRoute,
  ScheduleTravelRoute: ScheduleTravelRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  ScheduleConnectionConnectionIdRoute: ScheduleConnectionConnectionIdRoute,
  ScheduleCourseCodeRoute: ScheduleCourseCodeRoute,
  ScheduleResultResultIdRoute: ScheduleResultResultIdRoute,
}

const ScheduleRouteWithChildren = ScheduleRoute._addFileChildren(
  ScheduleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  PlanRoute: PlanRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ScheduleRoute: ScheduleRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  AdminDecisionsRoute: AdminDecisionsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminGradesRoute: AdminGradesRoute,
  AdminKitRoute: AdminKitRoute,
  AuthTestRoute: AuthTestRoute,
  PlanSharedRoute: PlanSharedRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  ReviewsMineRoute: ReviewsMineRoute,
  ReviewsPolicyRoute: ReviewsPolicyRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  TodoConnectRoute: TodoConnectRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  TodoIndexRoute: TodoIndexRoute,
  ReviewsCoursesCodeRoute: ReviewsCoursesCodeRoute,
  ReviewsInstructorsIdRoute: ReviewsInstructorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
